services:
  app:
    build: .
    container_name: pcto_gestorfrota_api
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://${CLOUD_DB_HOST}:${CLOUD_DB_PORT}/${CLOUD_DB_NAME}
      DB_USER: ${CLOUD_DB_USER}
      DB_PASSWORD: ${CLOUD_DB_PASSWORD}
      DB_DRIVER: ${CLOUD_DB_DRIVER}
      DB_PLATFORM: ${CLOUD_DB_PLATAFORM}
      JWT_SECRET: ${JWT_SECRET}
      SPRING_PROFILES_ACTIVE: prod
