services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: gestorfrota
      POSTGRES_USER: api
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gestor_app -d gestor"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: gestor_api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/gestorfrota
      SPRING_DATASOURCE_USERNAME: api
      SPRING_DATASOURCE_PASSWORD: 12345678
      APP_ADMIN_INSERT_ENABLED: "true"
      APP_ADMIN_NAME: Admin
      APP_ADMIN_REGISTRATION: 11235824
      APP_ADMIN_PASSWORD: 1234
      JWT_SECRET: muito-secreto
    ports:
      - "8080:8080"

volumes:
  postgres_data:
